spring.application.name=ProductService
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/productservice?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=Hung@010204

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

gemini.api.key=AQ.Ab8RN6Lmjk2-3gkUTTB0L5fsU_pC36Pkq9d6OZj0M85sX8qoZw
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=