server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: AuthService
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/addresses/**, /api/locations/**
          filters:
            - AuthenticationFilter

        - id: ProductService
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/chat/**
          filters:
            - AuthenticationFilter

        - id: CartService
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter
 
        - id: OrderService
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**,/api/vouchers/**
          filters:
            - AuthenticationFilter
            
        - id: payos-callback
          uri: http://localhost:8084
          predicates:
            - Path=/api/payment/payos/** # Dấu ** này bao gồm cả /return và /cancel
            
        - id: FlashSaleService
          uri: http://localhost:8085
          predicates:
            - Path=/api/flash-sales/**
          filters:
            - AuthenticationFilter